"""Write the accessor pages of the API reference (docs/src/content/docs/reference/*.mdx).

Each page embeds one method per ``<Autodoc>`` block, in source order, under a heading of its own:
starlight-pydocs renders the method, and the heading gives Starlight's "On this page" panel an
entry for it (the panel only sees the page's own Markdown headings; the CSS in custom.css hides the
duplicate). The module pages under /api/plasma_plots/ are generated by starlight-pydocs itself.

Run from the repo root after adding, removing or reordering accessor methods:

    python scripts/accessor_pages.py            # write the pages
    python scripts/accessor_pages.py --check    # fail if they are out of date (tests/test_accessor_pages.py)
"""

from __future__ import annotations

import sys
from pathlib import Path

import griffe

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "src" / "content" / "docs" / "reference"

NOTE = """:::note[Where the accessors come from]
The examples use output of a Struphy `Output`, which loads plasma-plots and its
`.plasma` accessors. For other xarray data, run `import plasma_plots` first (see
[Getting started](/plasma-plots/guides/getting-started/#loading-plasma-plots)).
:::"""

# slug: (title, description, intro, [(class path, section heading), ...])
PAGES = {
    "plot": (
        "array.plasma.plot",
        "Plots of one labeled array: time series, slices, animations, spectra, 3-D views.",
        "Plots of one labeled `xarray.DataArray`, as `array.plasma.plot.<method>(...)`. Each method selects the "
        "dimensions it doesn't draw by keyword (an integer is a position, `t=-1` the last; a float the nearest "
        "value), draws, and returns a `PlotResult` (or an animation or a PyVista plotter).",
        [
            ("accessors.ArrayPlots", "array.plasma.plot"),
            ("accessors.SliceView", "SliceView, returned by plot.view()"),
        ],
    ),
    "analysis": (
        "array.plasma.analysis",
        "Diagnostics of one labeled array: fits, norms, errors, spectra, vector calculus.",
        "Numerical diagnostics of one labeled `xarray.DataArray`, as `array.plasma.analysis.<method>(...)`. They "
        "return labeled arrays and Datasets, so their results can be plotted with `.plasma.plot` in turn.",
        [("accessors.ArrayAnalysis", "array.plasma.analysis")],
    ),
    "data": (
        "array.plasma.data",
        "The selected data behind every plot, without drawing it.",
        "Every plot on `array.plasma.plot` has a twin here, as `array.plasma.data.<method>(...)`, that does the "
        "same selection and returns the labeled `xarray` object instead of a figure. See the "
        "[Selecting data](/plasma-plots/guides/data/) guide.",
        [("accessors.ArrayData", "array.plasma.data")],
    ),
    "dataset": (
        "dataset.plasma",
        "Plots, diagnostics and data of marker Datasets such as orbits.",
        "Plots, diagnostics and data of an `xarray.Dataset` with per-marker variables, such as an orbits product.",
        [
            ("accessors.DatasetPlots", "dataset.plasma.plot"),
            ("accessors.DatasetAnalysis", "dataset.plasma.analysis"),
            ("accessors.DatasetData", "dataset.plasma.data"),
        ],
    ),
    "output": (
        "out.plot and out.analysis",
        "Whole-run plots and diagnostics of a Struphy Output.",
        "Plots and diagnostics of a whole run, on a Struphy `Output` object. `out.plot()` on its own draws the "
        "scalar overview.",
        [
            ("output_accessors.OutputPlots", "out.plot"),
            ("output_accessors.ProfilePlots", "out.plot.profile"),
            ("output_accessors.OutputAnalysis", "out.analysis"),
        ],
    ),
}


def _mdx_text(text: str) -> str:
    """reST text for MDX: double backticks to single, and { and < escaped outside code spans."""
    parts = text.replace("``", "`").split("`")
    for i in range(0, len(parts), 2):
        parts[i] = parts[i].replace("{", "\\{").replace("<", "&lt;")
    return "`".join(parts)


def methods(cls):
    """Public methods and properties of a class, in source order."""
    members = [
        m
        for name, m in cls.members.items()
        if not name.startswith("_")
        and not m.is_alias
        and (m.is_function or "property" in m.labels)
    ]
    return sorted(members, key=lambda m: m.lineno or 0)


def render(package, slug) -> str:
    title, description, intro, classes = PAGES[slug]
    order = list(PAGES).index(slug) + 1
    lines = [
        "---",
        f'title: "{title}"',
        f'description: "{description}"',
        "sidebar:",
        f"  order: {order}",
        "---",
        "",
        "{/* Written by scripts/accessor_pages.py; edit that script, not this page. */}",
        "",
        "import { Autodoc } from 'starlight-pydocs/components';",
        "",
        intro,
        "",
        NOTE,
        "",
    ]
    for path, heading in classes:
        cls = package[path]
        lines += [f"## {heading}", ""]
        summary = cls.docstring.value.strip().splitlines()[0] if cls.docstring else ""
        if summary:
            lines += [_mdx_text(summary), ""]
        for method in methods(cls):
            lines += [
                f"### `{method.name}`",
                "",
                f'<Autodoc name="plasma_plots.{path}.{method.name}" package="plasma_plots" headingLevel={{3}} />',
                "",
            ]
    return "\n".join(lines).rstrip() + "\n"


def main():
    package = griffe.load(
        "plasma_plots", search_paths=[str(ROOT / "src")], docstring_parser="numpy"
    )
    stale = []
    for slug in PAGES:
        path = OUT / f"{slug}.mdx"
        text = render(package, slug)
        if "--check" in sys.argv:
            if not path.exists() or path.read_text() != text:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(text)
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print(
            "out of date (run python scripts/accessor_pages.py):\n" + "\n".join(stale)
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
